# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import service
from google.protobuf import service_reflection
from google.protobuf import descriptor_pb2


_CONTROL_OPCODE = descriptor.EnumDescriptor(
  name='OpCode',
  full_name='FuzzyAgent.Control.OpCode',
  filename='OpCode',
  values=[
    descriptor.EnumValueDescriptor(
      name='Audio', index=0, number=1,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='Graphic', index=1, number=2,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='URL', index=2, number=3,
      options=None,
      type=None),
  ],
  options=None,
)

_CONTROL_AUDIOTYPES = descriptor.EnumDescriptor(
  name='AudioTypes',
  full_name='FuzzyAgent.Control.AudioTypes',
  filename='AudioTypes',
  values=[
    descriptor.EnumValueDescriptor(
      name='AudioFormatLinearPCM', index=0, number=1,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='AudioFormatAC3', index=1, number=2,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='AudioFormat60958AC3', index=2, number=3,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='AudioFormatAppleIMA4', index=3, number=4,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='AudioFormatMPEG4AAC', index=4, number=5,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='AudioFormatMPEG4CELP', index=5, number=6,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='AudioFormatMPEG4HVXC', index=6, number=7,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='AudioFormatMPEG4TwinVQ', index=7, number=8,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='AudioFormatMACE3', index=8, number=9,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='AudioFormatMACE6', index=9, number=10,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='AudioFormatULaw', index=10, number=11,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='AudioFormatALaw', index=11, number=12,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='AudioFormatQDesign', index=12, number=13,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='AudioFormatQDesign2', index=13, number=14,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='AudioFormatQUALCOMM', index=14, number=15,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='AudioFormatMPEGLayer1', index=15, number=16,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='AudioFormatMPEGLayer2', index=16, number=17,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='AudioFormatMPEGLayer3', index=17, number=18,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='AudioFormatTimeCode', index=18, number=19,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='AudioFormatMIDIStream', index=19, number=20,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='AudioFormatParameterValueStream', index=20, number=21,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='AudioFormatAppleLossless', index=21, number=22,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='AudioFormatMPEG4AAC_HE', index=22, number=23,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='AudioFormatMPEG4AAC_LD', index=23, number=24,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='AudioFormatMPEG4AAC_HE_V2', index=24, number=25,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='AudioFormatMPEG4AAC_Spatial', index=25, number=26,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='AudioFormatAMR', index=26, number=27,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='AudioFormatAudible', index=27, number=28,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='AudioFormatiLBC', index=28, number=29,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='AudioFormatDVIIntelIMA', index=29, number=30,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='AudioFormatMicrosoftGSM', index=30, number=31,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='AudioFormatAES3', index=31, number=32,
      options=None,
      type=None),
  ],
  options=None,
)


_CONTROL = descriptor.Descriptor(
  name='Control',
  full_name='FuzzyAgent.Control',
  filename='FuzzyAgent.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='opcode', full_name='FuzzyAgent.Control.opcode', index=0,
      number=1, type=5, cpp_type=1, label=2,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='sequence', full_name='FuzzyAgent.Control.sequence', index=1,
      number=2, type=5, cpp_type=1, label=2,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='type', full_name='FuzzyAgent.Control.type', index=2,
      number=3, type=5, cpp_type=1, label=2,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='data', full_name='FuzzyAgent.Control.data', index=3,
      number=4, type=12, cpp_type=9, label=2,
      default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
    _CONTROL_OPCODE,
    _CONTROL_AUDIOTYPES,
  ],
  options=None)


_RESPONSE = descriptor.Descriptor(
  name='Response',
  full_name='FuzzyAgent.Response',
  filename='FuzzyAgent.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='return_code', full_name='FuzzyAgent.Response.return_code', index=0,
      number=1, type=5, cpp_type=1, label=2,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)



class Control(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _CONTROL

class Response(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _RESPONSE

